#
# /etc/login_menu.conf
# Fichier de configuration du menu des options.
#

# Chaque entrée dans le menu doit être écrite de la manière suivante:
# [ NOM ; COMMANDE ; QUITTER ]
# > NOM est le nom de l'entrée tel qu'affiché dans le menu
# > COMMANDE est la commande à exécuter
# > QUITTER indique si le menu doit quitter en exécutant cette commande (entrez TRUE ou FALSE)

# Il ne faut pas mettre de guillemets nulle part sauf si votre commande l'exige.
# Les crochets et les point-virgules doivent OBLIGATOIREMENT être séparés du texte par des espaces!
# Tout texte n'étant pas placé entre crochets sera ignoré (les # sont donc facultatifs).


[ Login CLI ; agetty - ; TRUE ]
[ Suspendre ; systemctl suspend ; FALSE ]
[ Redémarrer ; reboot ; TRUE ]
[ Éteindre ; shutdown now ; TRUE ]
